---
title: "Data Exploration"
author: "Mia Isaacs"
date: "2024-12-08"
output: github_document
---

### load packages

```{r}
library(tidyverse)
library(Biostrings)
```

### clean and limit dataset to only necessary variables

```{r}
dengueIgG_df = read_csv("data/Dengue_data_analysis_IgG.csv") |> 
  janitor::clean_names() |> 
  distinct(probe_sequence, .keep_all = TRUE) |> 
  select(probe_sequence, starts_with("uwa")) |> 
  rename_with(~ str_remove_all(., c("uwa_" = "", "_ig_g" = "")))

view(dengueIgG_df)
```

### separate into data frames based on group and time point

*DENV1 acute*
```{r DENV1 serotype acute}
denv1a_df <- dengueIgG_df |> 
  select(probe_sequence, contains("_d1_")) |> 
  select(probe_sequence, contains("acute"))

view(denv1a_df)
```

*DENV1 convalescent*
```{r DENV1 serotype conv}
denv1c_df <- dengueIgG_df |> 
  select(probe_sequence, contains("_d1_")) |> 
  select(probe_sequence, contains("conv"))

view(denv1c_df)
```

```{r DENV2 serotype}
denv2_df <- dengueIgG_df |> 
  select(probe_sequence, contains("_d2_"))

view(denv2_df)
```

```{r DENV3 serotype}
denv3_df <- dengueIgG_df |> 
  select(probe_sequence, contains("_d3_"))

view(denv3_df)
```

```{r DENV34 serotype}
denv34_df <- dengueIgG_df |> 
  select(probe_sequence, contains("d3d4"))

view(denv34_df)
```

```{r DENV4 serotype}
denv4_df <- dengueIgG_df |> 
  select(probe_sequence, contains("_d4_"))

view(denv4_df)
```

```{r nc control}
nc_df <- dengueIgG_df |> 
  select(probe_sequence, contains("nc"))

view(nc_df)
```

```{r z}
z_df <- dengueIgG_df |> 
  select(probe_sequence, contains("_z_"))

view(z_df)
```

```{r zd}
zd_df <- dengueIgG_df |> 
  select(probe_sequence, contains("_zd_"))

view(zd_df)
```

```{r zdyfv}
zdyfv_df <- dengueIgG_df |> 
  select(probe_sequence, contains("zdyfv"))

view(zdyfv_df)
```

```{r zyfv}
zyfv_df <- dengueIgG_df |> 
  select(probe_sequence, contains("zyfv"))

view(zyfv_df)
```

### export probe sequence as FASTA file
```{r}
probe_sequences <- dengueIgG_df$probe_sequence
names(probe_sequences) <- paste0("Probe_", seq_along(probe_sequences))
writeXStringSet(AAStringSet(probe_sequences), filepath = "probe_sequences.fasta")
```

### import alignnment table
```{r}
geneious_table1 <- read.csv("data/NC_001477_Annotations_DENV1.csv", header = TRUE)

head(geneious_table1)
```

```{r}
geneious_table1 <- geneious_table1 |> 
  mutate(
    Minimum = as.numeric(gsub(">", "", Minimum)),  
    Maximum = as.numeric(gsub(">", "", Maximum)),  
    Length = as.numeric(gsub(">", "", Length))    
  )
```

```{r}
geneious_table1 <- geneious_table1 |> 
  arrange(Minimum) |>                
  distinct(Name, .keep_all = TRUE) |>  
  mutate(Probe_Number = row_number()) 
```

```{r}
visual_test <- denv1a_df |> 
  left_join(geneious_table1, by = c("probe_sequence" = "Sequence.Name"))
```

```{r}
ggplot(visual_test, aes(x = Probe_Number, y = intensity_value, color = Type)) +
  geom_point() +
  labs(
    title = "Probe Binding Positions on DENV Proteome",
    x = "Probe Number (Ordered by Position)",
    y = "Intensity Value",
    color = "Region Type"
  ) +
  theme_minimal()
```






